- name: copy Corefile
  copy:
    src: files/coredns
    dest: /home/me

- name: run coredns container
  docker_container:
    name: coredns
    image: coredns/coredns
    restart_policy: always
    network_mode: host
    volumes:
      - /home/me/coredns:/root
    command: -conf /root/Corefile
    state: started

- name: open ports
  firewalld:
    zone: external
    service: dns
    state: enabled
    permanent: yes
    immediate: yes 

- name: open ports
  firewalld:
    zone: home
    service: dns
    state: enabled
    permanent: yes
    immediate: yes 