# Tasks for wireguard role

- name: Install wireguard and other prequisites on the server
  include: 'wireguard_install.yml'
  tags: install_wireguard

- name: Generate client keys and enable wireguard interface
  include: 'generate_keys.yml'
  tags: generate_keys

- name: Set up nat and firewall rules
  include: 'firewalld_setup.yml'
  tags: nat_and_firewall

- name: Download client configs
  include: 'download_configs.yml'
  tags: download_configs

- name: Open ports
  include: firewalld_setup.yml
  tags:
    - wireguard
    - wireguard_firewalld

# - name: Setup unbound dns service
#   include: unbound.yml
#   tags:
#     - unbound